" For Vim in Terminal
set number
set relativenumber

set cindent
set autoindent
set ts=4 sw=4
set expandtab

set undofile
set swapfile
set backup

set undodir=$HOME/.config/vim/undo
set directory=$HOME/.config/vim/swap
set backupdir=$HOME/.config/vim/backup

set clipboard=unnamedplus

set timeoutlen=1000 ttimeoutlen=0

set showcmd

nnoremap j gj
nnoremap k gk

cnoremap <C-t> terminal<CR>
cnoremap <C-S-t> vertical terminal<CR>

cnoremap <C-;> terminal bash -c ""<LEFT>
cnoremap <C-S-;> vertical terminal bash -c ""<LEFT>

tnoremap <C-S-v> <C-w>"+
tnoremap <C-w> <C-\><C-n>

source $HOME/.config/vim/scripts/wayland_clipboard.vim

if has('gui_running')
    source $HOME/.config/vim/scripts/gui.vim
endif
