" Minimal Configs
set number
set relativenumber

set cindent
set autoindent
set ts=4 sw=4
set expandtab

set undofile
set swapfile
set backup

set undodir=$HOME/.config/vim/undo
set directory=$HOME/.config/vim/swap
set backupdir=$HOME/.config/vim/backup

set showcmd
set clipboard=unnamed
set shell=pwsh

autocmd VimEnter * set textwidth=0

" Extra
let g:mapleader = ","

source $HOME/.config/vim/scripts/compilation_mode/main.vim

source $HOME/.config/vim/scripts/utils/term_utils.vim

if has('gui_running')
    source $HOME/.config/vim/scripts/gui.vim
endif

if has('wayland')
    source $HOME/.config/vim/scripts/wayland_clipboard.vim
endif
